import Header from "@/components/common/header/Header";
import { Providers } from "@/utils/service/TanstakProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "swiper/css";
import Footer from "@/components/common/footer/Footer";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-secondary`}
      >
        <div className="flex flex-col justify-between px-0 mx-auto max-w-[1400px] h-screen">
          <Providers>
            <Header />
            {children}
            <Footer />
            <Toaster />
          </Providers>
        </div>
      </body>
    </html>
  );
}
